#!/bin/sh
alias rufconf="nano ~/.config/ruff/ruff.toml"
alias fff="cd /sdcard/_static"
alias ffff="cd /sdcard/Download"
alias etc="cd ~/../usr/etc"
alias pc4="proxychains4"
alias safe_mv="safe_mv 2>/dev/null"
alias safe_cp="safe_cp 2>/dev/null"
alias cpyco="cpyco 2>/dev/null"
alias dmp="dmp 2>/dev/null"
alias ddd="ddd 2>/dev/null"
alias lazydir="cd ~/.local/share/nvim/lazy"
alias masondir="cd ~/.local/share/nvim/mason"
alias taplo="taplo --color=always --verbose"


alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias dnss="cat ~/../usr/etc/resolv.conf"
alias aar="apt autoremove"
alias aptr="apt install --reinstall"
alias aptri="apt install --reinstall"
alias pkr="apt install --reinstall"
alias aptp="apt purge"
alias pku="apt remove"
alias apts="apt search"
alias ccc="cat"
alias cf="cd"
alias cx="cd"
alias lbb='cd $HOME/.local/bin'
alias mm="cd $HOME/isaac/may"
alias ubin="cd $PREFIX/bin"
alias spkg2="cd /data/data/com.termux/files/home/.local/lib/python3/site-packages"
alias spkg="cd /data/data/com.termux/files/usr/lib/python3.13/site-packages"
alias spkg13="cd /data/data/com.termux/files/home/.local/lib/python3.13/site-packages"
alias spkg12="cd /data/data/com.termux/files/home/.local/lib/python3.12/site-packages"
alias temp="cd /data/data/com.termux/files/usr/tmp"
alias sdcard="cd /sdcard"
alias sdd="cd /sdcard"
alias ffg='cd /sdcard/_static'
alias dcim="cd /sdcard/dcim"
alias dic="cd /sdcard/dic"
alias doc="cd /sdcard/doc"
alias whl="cd /sdcard/whl"
alias inc="cd ~/../usr/include"
alias lib="cd ~/../usr/lib"
alias shar="cd ~/../usr/share"
alias rss="cd ~/.cargo/registry/src"
alias nconf="cd ~/.config/nvim"
alias lob="cd ~/.local"
alias neodir="cd ~/.local/share/nvim/lazy"
alias bbb='cd ~/bashbin'
alias bb="cd ~/bin"
alias ee="cd ~/isaac/dec"
alias feb="cd ~/isaac/feb"
alias q1="cd ~/isaac/may/gapgpt/q"
alias dh="cd ~/isaac/may/pkgs/dh/src/dh"
alias repis="cd ~/repos"
alias repos="cd ~/repos"
alias bbbb="cd ~/sbin"
alias sbin="cd ~/sbin"
alias tmp="cd ~/tmp"
alias c="clear"
alias x="exit"
alias fde="fd -e"
alias fdd="find . -type d -name"
alias ff="find . -type f -name"
alias ga="git add ."
alias gb="git branch"
alias gba="git branch -a"
alias gch="git checkout"
alias gc="git commit -m"
alias gits="git status"
alias k="kibi"
alias nnn="n ~/.bashrc"
alias nn="n ~/.config/bash.d/bash_aliases.sh"
alias n3="n ~/.config/bash.d/bash_functions.sh"
alias n="nano"
alias m="nvim"
alias mconf="nano ~/.config/nvim/init.lua"
alias py="python"
alias pipi="python -m pip install --no-index --find-links=/sdcard/whl --force-reinstall"
alias py3="python3"
alias rff="rm -rf"
alias rfs="rm -rf *"
alias mv="safe_mv"
alias cp="safe_cp"
alias ss="source ~/.bashrc"
alias sss='source ~/bashbin/bsh.sh'
alias vvv="source ~/venv/bin/activate"
alias to="termux-open"
alias ts="tree-sitter"
alias tsb="tree-sitter build"
alias tyc="ty check"
alias unc="uncomment --remove-doc ."
alias wp="wheel pack"
alias wa="which -a"
alias wai="whoami"
alias apti="yes | apt install"




alias -- -='cd -'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias .3='cd ../../../'
alias .4='cd ../../../../'
alias .5='cd ../../../../../'
alias .6='cd ../../../../../../'
alias 1='cd -'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'
alias _='sudo'
alias aar='apt autoremove'
alias afind='ack -il'
alias apti='yes | apt install'
alias aptp='apt purge'
alias aptr='apt install --reinstall'
alias aptri='apt install --reinstall'
alias apts='apt search'
alias bashconfig='nano ~/.bashrc'
alias bb='cd ~/bin'
alias bbb='cd ~/bashbin'
alias bbbb='cd ~/sbin'
alias c='clear'
alias ccc='cat'
alias cd='_omb_directories_cd'
alias cd..='cd ../'
alias cf='cd'
alias cic='bind "set completion-ignore-case on"'
alias cp='safe_cp'
alias cpyco='cpyco 2>/dev/null'
alias cx='cd'
alias d='bm -d'
alias dcim='cd /sdcard/dcim'
alias ddd='ddd 2>/dev/null'
alias dh='cd ~/isaac/may/pkgs/dh/src/dh'
alias dic='cd /sdcard/dic'
alias dmp='dmp 2>/dev/null'
alias dnss='cat ~/../usr/etc/resolv.conf'
alias doc='cd /sdcard/doc'
alias ee='cd ~/isaac/dec'
alias egrep='grep -E --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn}'
alias etc='cd ~/../usr/etc'
alias fdd='find . -type d -name'
alias fde='fd -e'
alias feb='cd ~/isaac/feb'
alias ff='find . -type f -name'
alias fff='cd /sdcard/_static'
alias ffff='cd /sdcard/Download'
alias ffg='cd /sdcard/_static'
alias fgrep='grep -F --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn}'
alias fix_stty='stty sane'
alias fix_term='echo -e "\033c"'
alias g='bm -g'
alias ga='git add .'
alias gaa='command git add --all'
alias gam='command git am'
alias gama='command git am --abort'
alias gamc='command git am --continue'
alias gams='command git am --skip'
alias gamscp='command git am --show-current-patch'
alias gap='command git apply'
alias gapa='command git add --patch'
alias gapt='command git apply --3way'
alias gau='command git add --update'
alias gav='command git add --verbose'
alias gb='git branch'
alias gbD='command git branch --delete --force'
alias gba='git branch -a'
alias gbd='command git branch -d'
alias gbda='command git branch --no-color --merged | command grep -vE "^([+*]|\s*($(git_main_branch)|$(git_develop_branch))\s*$)" | command xargs git branch --delete 2>/dev/null'
alias gbg='LANG=C command git branch -vv | grep ": gone\]"'
alias gbgD='LANG=C command git branch --no-color -vv | grep ": gone\]" | awk '\''{print $1}'\'' | command xargs git branch -D'
alias gbgd='LANG=C command git branch --no-color -vv | grep ": gone\]" | awk '\''{print $1}'\'' | command xargs git branch -d'
alias gbl='command git blame -b -w'
alias gbm='command git branch --move'
alias gbnm='command git branch --no-merged'
alias gbr='command git branch --remote'
alias gbs='command git bisect'
alias gbsb='command git bisect bad'
alias gbsc='command git branch --show-current'
alias gbsg='command git bisect good'
alias gbsn='command git bisect new'
alias gbso='command git bisect old'
alias gbsr='command git bisect reset'
alias gbss='command git bisect start'
alias gc='git commit -m'
alias gc!='command git commit --verbose --amend'
alias gca='command git commit --verbose --all'
alias gca!='command git commit --verbose --all --amend'
alias gcam='command git commit --all --message'
alias gcan!='command git commit --verbose --all --no-edit --amend'
alias gcans!='command git commit --verbose --all --signoff --no-edit --amend'
alias gcas='command git commit --all --signoff'
alias gcasm='command git commit --all --signoff --message'
alias gcb='command git checkout -b'
alias gcd='command git checkout "$(git_develop_branch)"'
alias gcf='command git config --list'
alias gch='git checkout'
alias gcl='command git clone --recursive'
alias gclean='command git clean -fd'
alias gcm='command git checkout "$(git_main_branch)"'
alias gcmsg='command git commit --message'
alias gcn!='command git commit --verbose --no-edit --amend'
alias gco='command git checkout'
alias gcor='command git checkout --recurse-submodules'
alias gcount='command git shortlog --summary --numbered'
alias gcp='command git cherry-pick'
alias gcpa='command git cherry-pick --abort'
alias gcpc='command git cherry-pick --continue'
alias gcps='command git cherry-pick -s'
alias gcs='command git commit --gpg-sign'
alias gcsm='command git commit --signoff --message'
alias gcss='command git commit --gpg-sign --signoff'
alias gcssm='command git commit --gpg-sign --signoff --message'
alias gd='command git diff'
alias gdca='command git diff --cached'
alias gdct='command git describe --tags `git rev-list --tags --max-count=1`'
alias gdcw='command git diff --cached --word-diff'
alias gds='command git diff --staged'
alias gdt='command git diff-tree --no-commit-id --name-only -r'
alias gdtool='command git difftool -d'
alias gdup='command git diff @{upstream}'
alias gdw='command git diff --word-diff'
alias gf='command git fetch'
alias gfa='command git fetch --all --prune'
alias gfg='command git ls-files | grep'
alias gfo='command git fetch origin'
alias gg='command git gui citool'
alias gga='command git gui citool --amend'
alias ggpull='command git pull origin "$(git_current_branch)"'
alias ggpur='ggu'
alias ggpush='command git push origin "$(git_current_branch)"'
alias ggsup='command git branch --set-upstream-to="origin/$(git_current_branch)"'
alias ghh='command git help'
alias gignore='command git update-index --assume-unchanged'
alias gignored='command git ls-files -v | grep "^[[:lower:]]"'
alias git-svn-dcommit-push='command git svn dcommit && command git push github "$(git_main_branch):svntrunk"'
alias gits='git status'
alias gke='\gitk --all $(git log --walk-reflogs --pretty=%h)'
alias glg='command git log --stat'
alias glgg='command git log --graph'
alias glgga='command git log --graph --decorate --all'
alias glgm='command git log --graph --max-count=10'
alias glgp='command git log --stat -p'
alias glo='command git log --oneline --decorate'
alias glod='command git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset"'
alias glods='command git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset" --date=short'
alias glog='command git log --oneline --decorate --graph'
alias gloga='command git log --oneline --decorate --graph --all'
alias glol='command git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset"'
alias glola='command git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset" --all'
alias glols='command git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset" --stat'
alias glp='_git_log_prettily'
alias gluc='command git pull upstream "$(git_current_branch)"'
alias glum='command git pull upstream "$(git_main_branch)"'
alias gm='command git merge'
alias gma='command git merge --abort'
alias gmom='command git merge "origin/$(git_main_branch)"'
alias gms='command git merge --squash'
alias gmt='command git mergetool --no-prompt'
alias gmtl='command git mergetool --no-prompt'
alias gmtlvim='command git mergetool --no-prompt --tool=vimdiff'
alias gmtvim='command git mergetool --no-prompt --tool=vimdiff'
alias gmum='command git merge "upstream/$(git_main_branch)"'
alias gpd='command git push --dry-run'
alias gpf='command git push --force-with-lease'
alias gpf!='command git push --force'
alias gpoat='command git push origin --all && command git push origin --tags'
alias gpod='command git push origin --delete'
alias gpr='command git pull --rebase'
alias gpristine='command git reset --hard && command git clean --force -dfx'
alias gpsup='command git push --set-upstream origin "$(git_current_branch)"'
alias gpsupf='command git push --set-upstream origin "$(git_current_branch)" --force-with-lease'
alias gpu='command git push upstream'
alias gpv='command git push --verbose'
alias gra='command git remote add'
alias grb='command git rebase'
alias grba='command git rebase --abort'
alias grbc='command git rebase --continue'
alias grbd='command git rebase "$(git_develop_branch)"'
alias grbi='command git rebase --interactive'
alias grbm='command git rebase "$(git_main_branch)"'
alias grbo='command git rebase --onto'
alias grbom='command git rebase "origin/$(git_main_branch)"'
alias grbs='command git rebase --skip'
alias grep='grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn}'
alias grev='command git revert'
alias grh='command git reset'
alias grhh='command git reset --hard'
alias grhk='command git reset --keep'
alias grhs='command git reset --soft'
alias grm='command git rm'
alias grmc='command git rm --cached'
alias grmv='command git remote rename'
alias groh='command git reset "origin/$(git_current_branch)" --hard'
alias grrm='command git remote remove'
alias grs='command git restore'
alias grset='command git remote set-url'
alias grss='command git restore --source'
alias grst='command git restore --staged'
alias grt='cd $(command git rev-parse --show-toplevel || _omb_util_print ".")'
alias gru='command git reset --'
alias grup='command git remote update'
alias grv='command git remote --verbose'
alias gsb='command git status --short --branch'
alias gsd='command git svn dcommit'
alias gsh='command git show'
alias gsi='command git submodule init'
alias gsps='command git show --pretty=short --show-signature'
alias gsr='command git svn rebase'
alias gss='command git status --short'
alias gst='command git status'
alias gsta='command git stash save'
alias gstaa='command git stash apply'
alias gstall='command git stash --all'
alias gstc='command git stash clear'
alias gstd='command git stash drop'
alias gstl='command git stash list'
alias gstp='command git stash pop'
alias gsts='command git stash show'
alias gstu='gsta --include-untracked'
alias gsu='command git submodule update'
alias gsw='command git switch'
alias gswc='command git switch --create'
alias gswd='command git switch "$(git_develop_branch)"'
alias gswm='command git switch "$(git_main_branch)"'
alias gta='command git tag --annotate'
alias gts='command git tag --sign'
alias gtv='command git tag | sort -V'
alias gunignore='command git update-index --no-assume-unchanged'
alias gunwip='command git rev-list --max-count=1 --format="%s" HEAD | grep -q "\--wip--" && command git reset HEAD~1'
alias gup='command git pull --rebase'
alias gupa='command git pull --rebase --autostash'
alias gupav='command git pull --rebase --autostash --verbose'
alias gupom='command git pull --rebase origin "$(git_main_branch)"'
alias gupomi='command git pull --rebase=interactive origin "$(git_main_branch)"'
alias gupv='command git pull --rebase --verbose'
alias gwch='command git whatchanged -p --abbrev-commit --pretty=medium'
alias gwip='command git add -A; command git rm $(git ls-files --deleted) 2> /dev/null; command git commit --no-verify --no-gpg-sign --message "--wip-- [skip ci]"'
alias gwt='command git worktree'
alias gwta='command git worktree add'
alias gwtls='command git worktree list'
alias gwtmv='command git worktree move'
alias gwtrm='command git worktree remove'
alias inc='cd ~/../usr/include'
alias k='kibi'
alias la='ls -lhA'
alias lazydir='cd ~/.local/share/nvim/lazy'
alias lbb='cd $HOME/.local/bin'
alias less='less -FSRXc'
alias lib='cd ~/../usr/lib'
alias ll='ls -lAFh'
alias lob='cd ~/.local'
alias ls='_omb_util_alias_init_ls'
alias lsa='ls -lha'
alias m='nvim'
alias masondir='cd ~/.local/share/nvim/mason'
alias mconf='nano ~/.config/nvim/init.lua'
alias mkdir='mkdir -pv'
alias mm='cd /data/data/com.termux/files/home/isaac/may'
alias mv='safe_mv'
alias n='nano'
alias n3='n ~/.config/bash.d/bash_functions.sh'
alias nano='nano -W'
alias nconf='cd ~/.config/nvim'
alias neodir='cd ~/.local/share/nvim/lazy'
alias nn='n ~/.config/bash.d/bash_aliases.sh'
alias nnn='n ~/.bashrc'
alias ohmybash='nano ~/.oh-my-bash'
alias p='bm -p'
alias path='echo -e ${PATH//:/\\n}'
alias pc4='proxychains4'
alias pipi='python -m pip install --no-index --find-links=/sdcard/whl --force-reinstall'
alias pkr='apt install --reinstall'
alias pku='apt remove'
alias please='sudo'
alias po='popd'
alias py='python'
alias py3='python3'
alias q1='cd ~/isaac/may/gapgpt/q'
alias rd='rmdir'
alias repis='cd ~/repos'
alias repos='cd ~/repos'
alias rff='rm -rf'
alias rfs='rm -rf *'
alias rss='cd ~/.cargo/registry/src'
alias rufconf='nano ~/.config/ruff/ruff.toml'
alias s='bm -a'
alias safe_cp='safe_cp 2>/dev/null'
alias safe_mv='safe_mv 2>/dev/null'
alias sbin='cd ~/sbin'
alias sdcard='cd /sdcard'
alias sdd='cd /sdcard'
alias shar='cd ~/../usr/share'
alias show_options='shopt'
alias spkg='cd /data/data/com.termux/files/usr/lib/python3.13/site-packages'
alias spkg12='cd /data/data/com.termux/files/home/.local/lib/python3.12/site-packages'
alias spkg13='cd /data/data/com.termux/files/home/.local/lib/python3.13/site-packages'
alias spkg2='cd /data/data/com.termux/files/home/.local/lib/python3/site-packages'
alias src='source ~/.bashrc'
alias ss='source ~/.bashrc'
alias sss='source ~/bashbin/bsh.sh'
alias taplo='taplo --color=always --verbose'
alias temp='cd /data/data/com.termux/files/usr/tmp'
alias tmp='cd ~/tmp'
alias to='termux-open'
alias ts='tree-sitter'
alias tsb='tree-sitter build'
alias tyc='ty check'
alias ubin='cd /data/data/com.termux/files/usr/bin'
alias unc='uncomment --remove-doc .'
alias vvv='source ~/venv/bin/activate'
alias wa='which -a'
alias wai='whoami'
alias wget='wget -c'
alias whl='cd /sdcard/whl'
alias wp='wheel pack'
